version: "3.9"
services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_LICENSE_KEY=your-license-key-here
    volumes:
      - seq-data:/data

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backend
    restart: always
    command: sh -c "python3 manage.py makemigrations --noinput && python3 manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../src:/app
    depends_on:
      - seq
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-9mx7%17wg3sghh&2ep7b51tadw21tp57bdfd)=2ns=7_o4tnmy
      - DEBUG=True
      - ALLOWED_HOSTS=0.0.0.0

      - SEQ_LOG_LEVEL=INFO
      - FILE_LOG_LEVEL=INFO
      - CONSOLE_LOG_LEVEL=INFO
      - LOG_HANDLERS='console', 'file', 'seq'
      
      - SUPERUSER_USERNAME=admin
      - SUPERUSER_PASSWORD=!@#QWE123qwe

volumes:
  seq-data: