version: "3.9"
name: django-drf-clean-architecture-base
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
    - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_LICENSE_KEY=your-license-key-here
    volumes:
      - seq-data:/data

  db:
    container_name: db
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../envs/prod/db/.env

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backend
    restart: always
    command: sh -c "python3 manage.py makemigrations --noinput && python3 manage.py migrate --noinput && gunicorn infrastructure.server.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ../src:/app
    depends_on:
      - redis
      - seq
      - db
    ports:
      - "8000:8000"
    env_file:
      - ../envs/prod/backend/.env

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A core worker --loglevel=info
    restart: always
    volumes:
      - ../src:/app
    depends_on:
      - backend
  
  beat:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: beat
    command: celery -A core beat --loglevel=info
    restart: always
    volumes:
      - ../src:/app
    depends_on:
      - worker

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports: 
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - backend
      - worker
      - beat

volumes:
  seq-data:
  static_volume:
  media_volume:
  postgres_data: