version: "3.9"
services:

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
    - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_LICENSE_KEY=your-license-key-here
    volumes:
      - seq-data:/data

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backend
    restart: always
    command: sh -c "python3 manage.py makemigrations --noinput && python3 manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../src:/app
    depends_on:
      - redis
      - seq
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
      - ALLOWED_HOSTS=0.0.0.0

      - SEQ_LOG_LEVEL=INFO
      - FILE_LOG_LEVEL=INFO
      - CONSOLE_LOG_LEVEL=INFO
      - LOG_HANDLERS='console', 'file', 'seq'
      
      - SUPERUSER_USERNAME=admin
      - SUPERUSER_PASSWORD=!@#QWE123qwe

  worker:
    build: .
    container_name: worker
    command: celery -A core worker --loglevel=info
    restart: always
    volumes:
      - ../src:/app
    depends_on:
      - redis
      - seq
      - backend
  
  beat:
    build: .
    container_name: beat
    command: celery -A core beat --loglevel=info
    restart: always
    volumes:
      - ../src:/app
    depends_on:
      - redis
      - seq
      - backend
      - worker

  locust:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ../src/infrastructure/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://backend:8000
  
  locustworker:
    image: locustio/locust
    volumes:
      - ../src/infrastructure/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master

volumes:
  seq-data: